export const uam = [
    "Administracja",
    "Akustyka",
    "Amerykanistyka",
    "Analityka produktów spożywczych",
    "Analiza i przetwarzanie danych",
    "Aplikacje Internetu Rzeczy",
    "Archeologia",
    "Archeometria",
    "Astronomia",
    "Bałkanistyka",
    "Bezpieczeństwo narodowe",
    "Biofizyka",
    "Bioinformatyka",
    "Biologia",
    "Biologia i zdrowie człowieka",
    "Biotechnologia",
    "Central Europe in the International Perspective",
    "Central European and Balkan Studies",
    "Chemia",
    "Chemia aplikacyjna",
    "Chemia dla inżynierów",
    "Chemia materiałowa",
    "Chemia medyczna z projektowaniem leków",
    "Chemistry",
    "Dialog i doradztwo społeczne",
    "Digital Entrepreneurship",
    "Dziennikarstwo i komunikacja społeczna",
    "Edukacja artystyczna w zakresie sztuk muzycznych",
    "Edukacja artystyczna w zakresie sztuk plastycznych",
    "English Linguistics: Theories, Interfaces, Technologies",
    "English Studies: Literature and Culture",
    "Environmental Protection",
    "Etnolingwistyka",
    "Etnologia",
    "European Legal Studies",
    "Filmoznawstwo i kultura mediów",
    "Filologia angielska",
    "Filologia angielska w edukacji",
    "Filologia angielska z pedagogiką",
    "Filologia angielsko-celtycka",
    "Filologia angielsko-chińska",
    "Filologia arabska",
    "Filologia francuska",
    "Filologia germańska",
    "Filologia hiszpańska",
    "Filologia klasyczna",
    "Filologia koreańska",
    "Filologia polska",
    "Filologia polska jako obca",
    "Filologia rumuńska",
    "Filologia skandynawska",
    "Filologia wschodniosłowiańska",
    "Filologia włoska",
    "Filologie regionów",
    "Filozofia",
    "Fizyka",
    "Fizyka medyczna",
    "Geodezja i kartografia",
    "Geografia",
    "Geohazards and Climate Change",
    "Geoinformacja",
    "Geologia",
    "Geologia dla inżynierów",
    "Geologia inżynierska i hydrogeologia",
    "Geoslawistyka",
    "Global Communication",
    "Gospodarka i ekonomia w dziejach",
    "Gospodarka przestrzenna",
    "Governance of Organizations",
    "Groznawstwo",
    "Hebraistyka",
    "Historia",
    "Historia i polityka współczesna - interdyscyplinarne studia nauczycielskie",
    "Historia sztuki",
    "Humanistyka w szkole - polonistyczno-historyczne studia nauczycielskie",
    "Hydrologia, meteorologia i klimatologia",
    "Informacja naukowa i bibliotekoznawstwo",
    "Informatyka",
    "Informatyka kwantowa",
    "Japonistyka",
    "Język niemiecki i komunikacja w biznesie",
    "Językoznawstwo i zarządzanie informacją",
    "Kartografia i geomatyka",
    "Kierunek prawno-ekonomiczny",
    "Kognitywistyka",
    "Komunikacja europejska",
    "Komunikacja wizerunkowo-mediacyjna",
    "Kultura klasyczna",
    "Kulturoznawstwo",
    "Language, Mind, Technology",
    "Liberal Arts and Sciences",
    "Lingwistyka stosowana",
    "Literatura powszechna",
    "Matematyka",
    "Media interaktywne i widowiska",
    "Międzydziedzinowe Studia Indywidualne",
    "Muzykologia",
    "Nauczanie biologii i przyrody",
    "Nauczanie matematyki i informatyki",
    "Neurobiologia",
    "Nowe media w komunikacji",
    "Ochrona dóbr kultury",
    "Ochrona środowiska",
    "Optometria",
    "Optyka okularowa i optometria",
    "Pedagogika",
    "Pedagogika przedszkolna i wczesnoszkolna",
    "Pedagogika specjalna",
    "Polacy i Niemcy w Europie",
    "Politologia",
    "Polonistyczno-filozoficzne studia nauczycielskie",
    "Praca socjalna",
    "Prawo",
    "Prawo europejskie",
    "Produkcja audiowizualna",
    "Projektowanie kultury",
    "Psychologia",
    "Research in Cognitive Science",
    "Reżyseria dźwięku",
    "Sinologia",
    "Socjologia",
    "Stosunki międzynarodowe",
    "Studia niderlandystyczne",
    "Studia o Niemczech",
    "Studia o Polsce",
    "Studia slawistyczne",
    "Studia śródziemnomorskie",
    "Sztuka pisania",
    "Technologie informatyczne",
    "Technologie komputerowe",
    "Teologia",
    "Turkologia",
    "Turystyka i rekreacja",
    "Tłumaczenie konferencyjne polsko-angielskie",
    "Tłumaczenie kreatywne i specjalistyczne",
    "Tłumaczenie ustne",
    "Wiedza o teatrze",
    "Wschodoznawstwo",
    "Zaawansowane badania socjologiczne",
    "Zarządzanie i prawo w biznesie",
    "Zarządzanie państwem",
    "Zarządzanie w administracji lokalnej",
    "Zarządzanie środowiskiem",
    "Zintegrowane planowanie rozwoju",
    "Zmiany klimatu Ziemi"
];